Logo animation
tcoots88/Parse-Life pull request #8
Opened 2019-11-25 22:55 UTC by tcoots88

2019-11-25 23:13 UTC, phongvdoan commented on Logo/parse-life animation.html
> +  <link rel="stylesheet" href="parse-life animation.css">
Put in index.html

2019-11-25 23:15 UTC, phongvdoan requested changes

2019-11-25 23:15 UTC, phongvdoan commented on Logo/parse-life animation.html
> +  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cutive+Mono|Gruppo|Life+Savers|Oxygen+Mono|PT+Mono|Press+Start+2P|Turret+Road&display=swap" rel="stylesheet">
place in index.html

2019-11-25 23:15 UTC, phongvdoan commented on Logo/parse-life animation.html
> +      <br>
place in index.html

2019-11-26 00:11 UTC, tcoots88 commented
Added into index.html

2019-11-26 00:13 UTC, phongvdoan requested changes
place contents of parse-life animation .css into style/style.css, because the lower css will override the other

remove the link for parse-life animation.css inside index.html

2019-11-26 00:28 UTC, phongvdoan approved these changes

2019-11-26 00:28 UTC, merged